# Generated by Django 2.2.24 on 2024-04-15 13:29

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0016_lticonfiguration_lti_1p3_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonfiguration',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, default=None, help_text='Enable these settings course wide', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lticonfiguration',
            name='organization_slug',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Enable these settings organization wide', max_length=50, null=True),
        ),
    ]
